apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "apigroup.perception.com.tr/v1",
          "kind": "Hello",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "hello-operator"
            },
            "name": "hello-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-10-06T20:09:52Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.3
    operators.operatorframework.io/project_layout: ansible.sdk.operatorframework.io/v1
  name: hello-operator.v0.0.7
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Hello
      name: hellos.apigroup.perception.com.tr
      version: v1
  description: Sample Operator
  displayName: Hello Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAMgAAABTCAMAAADtJ7gsAAAKNWlDQ1BJQ0MgUHJvZmlsZQAAeJydU2dUk9kWPd/3pRdaQgSkhN6kSgkgUkIVkCpNVEISIJQQQ0KxF0QFRxQVEazIqIADjg5FxoooFgZFBewDMoio4+AoomJ5K7LW6Jo37715s3/ctde+59x7zz7nAtACgkXiLFQFIFMsk0b4e7Nj4+LZxC5AgQwEsAPg8bMlIZF+UQAAgb5cdnaEvzd8AQLwulexAtywCghjs+H/gypfIpUBIGEAMF0gzOYDIAUAkJErkyj0UQBgJqUrOIpTcGlsXDwAqqHgKZN82ueYSe6p4IJMsQAAVbxZIsgUKHg7AKzLkQsFAFgwABTmiIS5ANhNADDKkGeKALA3itxMIS8bAEdT6DIhPxUAZwsANGlUBBcANwOAREv5iid9xWXCPJmiKG6WJF8qSkmVsc345mw7FxcOO0CYmyGUyazCePx0nlTA5mZlSnjifIDJmj9DTeEtO9CX62Tn4uRkZW9t95VR/3Xzb0LR20n2MvxzzxBW5xftr+KyqgA4YwDYpi9a0g6A5jUAGne+aEZ7AZQLAJquflUPSzEvqTKZxNXGJjc311ok5FsrDP0D/zPgb+Cr+6wVx/1hD9tHmMyTZ8jYCt/4WRlZcik7W8LjC9lWfx7if5z41++YFiFMFkqFYr6QHS0S5orEKWxullggkomyxGyR+D818R+m/QmTcw0AjOqPwFxgDSpXmYD92gk4BhWwhN2Krv/Rt2ByNCh+Xoze8OTcfwby76eiJYolW5TyOY8bEcXmy6U5k3uKbwl4oIAyMEETdMEQzMAK7MEZ3MATfGEWhEIUxMF84EMqZIIUcmEJrIRCKIZNsA0qYA9UQw3Uw1FohhNwFi7AFbgGPXAX+mEInsIovIYJBEGICB1hIJqIHmKMWCL2CAeZifgiwUgEEockIimIGJEjS5DVSDFSilQg+5Aa5HvkOHIWuYR0I7eRAWQE+R15h2IoDWWiOqgJaoNyUC80CI1C56Ep6EJ0EVqAbkTL0Sr0MNqEnkWvoD1oP/oUHcMAo2IsTB+zwjgYFwvF4rFkTIotw4qwMqwKq8dasQ7sBtaPPcPe4gg4Bo6Ns8K54QJwc3B83ELcMtwGXAXuEK4J1467gRvAjeI+4ul4bbwl3hUfiI/Fp+Bz8YX4MvwBfCP+PL4HP4R/TSAQWARTgjMhgBBHSCMsJmwg7CI0EM4QugmDhDEikahJtCS6E0OJPKKMWEjcQTxMPE28ThwiviFRSXoke5IfKZ4kJq0ilZFqSadI10nDpAmyCtmY7EoOJQvI+eQScjW5lXyVPESeoKhSTCnulChKGmUlpZxSTzlPuUd5SaVSDagu1HCqiLqCWk49Qr1IHaC+panRLGhcWgJNTttIO0g7Q7tNe0mn003onvR4uoy+kV5DP0d/QH+jxFCyVgpUEigtV6pUalK6rvRcmaxsrOylPF95kXKZ8jHlq8rPVMgqJipcFZ7KMpVKleMqfSpjqgxVO9VQ1UzVDaq1qpdUH6sR1UzUfNUEagVq+9XOqQ0yMIYhg8vgM1YzqhnnGUNMAtOUGchMYxYzv2N2MUfV1dQd1KPV89Qr1U+q97MwlgkrkJXBKmEdZfWy3k3RmeI1RThl/ZT6KdenjGtM1fDUEGoUaTRo9Gi802Rr+mqma27WbNa8r4XTstAK18rV2q11XuvZVOZUt6n8qUVTj069o41qW2hHaC/W3q/dqT2mo6vjryPR2aFzTueZLkvXUzdNd6vuKd0RPYbeTD2R3la903pP2OpsL3YGu5zdzh7V19YP0Jfr79Pv0p8wMDWYY7DKoMHgviHFkGOYbLjVsM1w1EjPKMRoiVGd0R1jsjHHONV4u3GH8biJqUmMyVqTZpPHphqmgaaLTOtM75nRzTzMFppVmd00J5hzzNPNd5lfs0AtHC1SLSotrlqilk6WIstdlt3T8NNcpomnVU3rs6JZeVnlWNVZDVizrIOtV1k3Wz+3MbKJt9ls02Hz0dbRNsO22vaunZrdLLtVdq12v9tb2PPtK+1vTqdP95u+fHrL9BcOlg5Ch90OtxwZjiGOax3bHD84OTtJneqdRpyNnBOddzr3cZicMM4GzkUXvIu3y3KXEy5vXZ1cZa5HXX9zs3JLd6t1ezzDdIZwRvWMQXcDd577Pvf+meyZiTP3zuz30PfgeVR5PPQ09BR4HvAc9jL3SvM67PXc29Zb6t3oPc515S7lnvHBfPx9iny6fNV85/hW+D7wM/BL8avzG/V39F/sfyYAHxAUsDmgL1AnkB9YEzg6y3nW0lntQbSgyKCKoIfBFsHS4NYQNGRWyJaQe7ONZ4tnN4dCaGDoltD7YaZhC8N+DCeEh4VXhj+KsItYEtERyYhcEFkb+TrKO6ok6u4csznyOW3RytEJ0TXR4zE+MaUx/bE2sUtjr8RpxYniWuKJ8dHxB+LH5vrO3TZ3KMExoTChd57pvLx5l+Zrzc+Yf3KB8gLegmOJ+MSYxNrE97xQXhVvLCkwaWfSKJ/L385/KvAUbBWMCN2FpcLhZPfk0uTHKe4pW1JGUj1Sy1KfibiiCtGLtIC0PWnj6aHpB9M/ZcRkNGSSMhMzj4vVxOni9izdrLysbomlpFDSv9B14baFo9Ig6YFsJHtedouMKZPIOuVm8jXygZyZOZU5b3Kjc4/lqeaJ8zrzLfLX5w8v8lv07WLcYv7itiX6S1YuGVjqtXTfMmRZ0rK25YbLC5YPrfBfcWglZWX6yp9W2a4qXfVqdczq1gKdghUFg2v819QVKhVKC/vWuq3dsw63TrSua/309TvWfywSFF0uti0uK36/gb/h8jd235R/82lj8sauEqeS3ZsIm8Sbejd7bD5Uqlq6qHRwS8iWpq3srUVbX21bsO1SmUPZnu2U7fLt/eXB5S07jHZs2vG+IrWip9K7smGn9s71O8d3CXZd3+25u36Pzp7iPe/2ivbe2ue/r6nKpKpsP2F/zv5H1dHVHd9yvq05oHWg+MCHg+KD/YciDrXXONfU1GrXltShdfK6kcMJh6995/NdS71V/b4GVkPxETgiP/Lk+8Tve48GHW07xjlW/4PxDzsbGY1FTUhTftNoc2pzf0tcS/fxWcfbWt1aG3+0/vHgCf0TlSfVT5acopwqOPXp9KLTY2ckZ56dTTk72Lag7e652HM328Pbu84Hnb94we/CuQ6vjtMX3S+euOR66fhlzuXmK05XmjodOxt/cvypscupq+mq89WWay7XWrtndJ+67nH97A2fGxduBt680jO7p7t3Tu+tvoS+/luCW49vZ9x+cSfnzsTdFffw94ruq9wve6D9oOpn858b+p36Tw74DHQ+jHx4d5A/+PSX7F/eDxU8oj8qG9Ybrnls//jEiN/ItSdznww9lTydeFb4q+qvO5+bPf/hN8/fOkdjR4deSF98+n3DS82XB185vGobCxt78Drz9cR40RvNN4fect52vIt5NzyR+574vvyD+YfWj0Ef733K/PTpXwOY8/zaXQ1IAAAAYFBMVEX//////v////3+//7//Pv9/Pz/9/b/8vP96erowsPKh4jPPj/MMDC/Pj6BS0zPLi/NLi7MLzbMLi/MLTHMLizLLS7QLC7NLC/OKS7JLjLKLi/JLyzJLC6+LC2tKitRGRr1fpmEAAAZQ0lEQVR42t1b6bqbSLIEsSPELtYCvf9bTkRkoSO7u+ee/mz/mFuyjhCCqozcMwsH9+5eVVXX6aPit2aamu5xnmdd1/j76O73zkZTdX9yiI5rMS3VfP/m4N4N+76vzrltb8ZjPTBAfVkWRY5RlPfzPDrXjm5dR1y3uV8a275vbtNYsegTZxyOcHYbHOhYebzyEMcjFv3uxMHdjeN+DF0zjdO0dAJR5JlGypFlxXlUIyfeRy74y6PvexKs4xHLzgOIn6AHArKNIGQCUfhxbPvvTgogzbhX8zIt1boeQJELRV5wAEoYxln+OMihDnCq34DiByCgeh4GAZnApn4fQX5LKEL5L4D0vat2t1bVep5lnkmdaCEaD2CJ45RIgHMd52buf23MGL0nb5eI54HaPc/d0I5TSyA7IEwA20Pp1m/OC4m4bnQdDYPCyAnigCo149hMM0QEJFGaQ7u6YWiWqal+bTQY13HbtuDfgDNtO3QEImm0FdjaDCuZu353Xhg7jK5zx1lSn4TiWNfOzTOwyGaKNA6z8pyAYlqW+flrgxKBibvnc9SgWDiWZcDhvg8DTIZ6N8wzf/ruvEEHv9CtkkYJFMtUEce6Dt2yNI0bxuPM4yjOz2dFb/A7VKs3W2k5xs2QTNOweiADgaz9DDPhL99Vra6iAhWQBoWxVv1KdwuGYPTrMMClPbLwltHen83+7Yn/GUhv1tE0yzK1YwNnA4IRMdaqWTpob1Nt1U7PRST79m0b2d3xgKN6nNVInVzPIi9hEXsPIIDjquks4ltWAsgKt/XLQCSPfWxHaGrbNrAFKHOHKNLtywTFquB79r0RkH77F0Bg5rDx8wRDOtd14H8GJWvoEMdx7ju3AEiaEtzKONX/6qA8vECaaljW836nWeLs1MA4cYzwC4m0s6zl20Aggiw74V6bBfyHtWQxLGKRZ0dAgrHgghBA4KPX6tsc+r+AOPiqJ2bsYJ7FCRyQQwsUZ1meazdUPcxDVv99iZQ0c7qurnMNxZMilgMCjGTGdJU78zDK7sfg/gWD/otq0aT3cYabolHDvwMIVl4QDy0G4Ot6II1gSGz77wN55Pm5zuuwzK4aj1o41lGOvQeQHUshup+umelQfhnIPBIHjKNxDqkEGCd3qfBbFojA0PNuvW8C0v4LIKuE2cB/9Bu4X6QpcJgfhEFM0OE8Tmk1s0M28fxVHNB9hT0YQCUcML+XktRMuVGd5+UxrQdwTAyK/0K14DXAIVh2ta0w9TSrj4V+bwDveqwFaIzssMxm6auh/8ED09HTUbdz2/vzUsl+o6PFz1s/kuihV7qJC8GNuW33lbkEFCm9xcyyc6WoTFDv0KyJDhj23jGg9ZBMjygzt4qcb0vD2Q9Vh0QAmobVAcnhBcJ8p2Kg6hTYUzoD5Flw8cxO9617wlLhGrYKVzrkSqxhHNBX0Op1XZp237ulcZgEeg7171YcrkjKcUOzzPCJVCRSn0Q3zJ+9czwAdAsTLTc3NNt1RVK7d5DNMhEHPPOMeE9CNofIPSj+ty1yre05LeO4MuWShZRn5UgJk2GmkcgZ66PZO+BwJEUuZ3r2Q9ePqAFGzNYxe25BJALoyK/tXjFJAF9d1TBs01NV8EaOYXVARoRqB1ncLQklh9Ly1ANzPRFfJnB7Bqs6kOomxDeHMINMYyeDnz1SK3pQcHB1w7ztFLMBwRf8Nk1kP7jfIKc6fO7r6xG3bqCeHKosWFUIYkCG1BUshDahmqiamQ6BEgInumVCPEBsotlaPoXQAWwQzfmwYiFO4qywVPuB+AGsz6u4QgpfIWo2CDgokwZ61Gahu4ZcmVVB8cdpwSe0dpgJZO9nZje4zu0PxJDCJ/Asr6hVmUIh2IxUwimUOKBgOgOXCaZhWYdUBiHooPixYO926M4GGT9HBjWkDLia6TSzEQBB7ECxU5Yl5geXlMM5zNZKdTYBaSZHFGO1Dwu0FBLHWqCCMoKkhmdLSUNLBw0CsQDKmgQCCeNCVa6vD5HWU+AyzL1pmAIhCYdHLhh6xnZnbKkgT3d41ViaJ1OMnSUz9BAzI83FjwhDDZWjOojYmJWjZqOHJMHr1iysHFRp0eK6AcXjk9NUMJppbDZEiMq10BZaDhZBGUDbVDhaPRBoTIXsMKcI3iCou8wkYSkl4J1yidO8PpTyl4cbYe3I90E5HVDBKsC1cNM0rnvJOyiuGfLL8wc4qargDnOgm6yOMqM3hPCqBqrboSNwHo5qO8/TDOav1jxA02AdmT+uSKDWHcJBAriLT7AfpDUrNQpAmOjSChu6rKzwTYdCbQfMLLJV/SIdA2t2c8gpI8uAfAnMY9Eia8of8AaNo3Hpjscxtc2iG3B3u6jqSfM7uxlAB8dySFcWaShuAycmq4NXzHpNU2AeADk6Sb1rXFVJAXDUzfO2TZMBcUzaHdNFmN75NZB/kbm5RJOy3nXNE9PLdkCZo9tlAXOWFgbSvERts+prjhCB2dAKYJEQx0yD7NaEclh3YirOinqNFJjsLwV9kaasWidGmU0OIUS2EAJ9RHmsA38Eu0tkAGuPaMBiJugWujSoFtZjtvhYmYqu+8ECa+2UGhf1q0wpkWFeTa0YXECZA5Ldp2dQP+Q6Xa8irXi8atzxWKdJOJI4h3MqES2KXCzZ1lOKJRtDBFufoJIKccI5MHs81S2IOW+OEI3gSKSk4qh0BIgPyHOXM2yewX1ZMI1zM4M6iVtnGttEt185pcYwlIKp3AEdxRHoO+v0Rg1pNiZ6JKCUp6NfOJWEEg2RjtKr+BZn9Skjwq0EQsfC1eBWB9MacFvcmRF81CpIA/gCtAhranWzkohUfRDmZ2mICESS9mpc6KGDe2V2pBjCdA1MZJoFL4aCjfwvX7WI3zt34kjaVxgQyFLyYDkDlHAwTDF1B8wbUbpS0YYwmxa1nWFxA66Ku2eHUp1uuaIY4Y2pRHTR/DWMdOEqPj10Q8rg/CBIHEu7V5ZjDZp8DVIU+m7nlGVBQ3toHALxhvRgmcjt/CV1POhUrLLvjjusCTVlZ/KIGfkRCuAwbL2XCdCZePIaFKbUu2NavNyFozxRWuE+eCCWpa9c6stJIPYwpC3BiSHbiLO7LLWm03jRAqFwGWPQSv9OBjKyL+zwPSzLIj96pGn7OBCJ3E1GViqWMMUG+VImyAXsMPuAi1aS7zWbBD0YONQLgLQK2iwmH6aOt+ZnDbOhtjcK+BXV6s6KDhDZ0IE4a9wDvoI4yjB70MzPMkHiIZcANTYgqPXh+ME0ABkgmu40gTDOsP2HjEmOJGN3DuLozItQrRwrRs7B6o7yoIwQtB0a33Q0NxF9DtPq78AsobRkGA6loDUcGiocBKKGCbcs8HF61ZZrKmQj8GlD08ptglhYC8TkZ+9QDppF+wqzY/Y7tI0zV7+tOxsc7bwxuVk1t1g/yDkyW9mlwFABZCNajpgmGOjOYJLFoanxrphBJiAOwf1k4ACbZ+iRMW3gv3Mfl6flpexknlS2x9tX0DBOpCeTuWnGDaT8ofj6oIvH5ShBiAPO0c0E0sE7USAwNKcmMnw7g+RxN9RDJ78tqxhlFZSdGQCiwsNNzWH9VhCYxBT0YQJk8DAplOddPiIOQqZvsIf63K29KTr3CdLPXsomGXEknkf1hDOxwDrRi1Mej5Ppu2zxcTyIo4Y7RUBEMVYdproHeqcoKFriWH3slUe1NiQkutE15qyFD/NgGdabJudhyGChiBaUJUzNHRf0oXT+4Km5vUx7LxSzuk+jo9KXZoUyR1pstVj8h8y306R9MiCuA6N3bF4e6ymyO/ptGBovR6cB/eNZ2cuOnPVBKdg2A6PC0DAbfJjsmT6UrwKE+xopoxqXvMPkR0XcdmdtmTgMoVU0evMcuIG5UCZnoMSaeBXlTvrfQvZocmU8akmiPMbCnuSsvDDz4Y3ZRXBHP2Gi6YCTrp0HJmwEgrJDZo3cg6sxe2QXcGzNUfE0SaJK5nbNXaZHniptLpgLw/VRSzDC5BbfLJuGijslZ5Zdwz6Q9XYCQhzchrGS2zSBuaeFFgazUcF6GpT3pLYKukdoYoPPUA326AYYC5CgzFrpStHDXo1oJsFIBpGVIg4z2MepsoljnZjCeoIOlna6g7fAnpBWmH2nReG3jAB9Y1GhxMWIPKpqYvmkIEUfPTzH1sm3SBMoQPjSg87p2KyT2mNz0PetVlRdzlV0v93cVLBrZa5VhRoF+eQ8VSw+QAfScVUkiPQVU0vx2FStW+cRfULmytqfG2ZULAeLJt7SHa5qK3kXpSe57VisTBM7FBHnQ9k1bhuYKyETfGglUlU5pSws45kzsH3OFBsbD/v4JJuVcqO2QIydSJMiO9x71an04Q4hvs7sMqKVoNsZNpdFjQXX9xW2hZD2PB6gqUOpD3hWUaHtUXHrj/t4zJtbeL3KXLWqQKXTbgZvsUMCuS5smSLjbHqUzyALjQwwFkVh05FlHX21VtmBea8Q/yc3sC+A+hF3DE9snJINqNZZ+lZzADiwB+70sFHJkg5AWAiiTYB51UuBBrN6qjYrvdnKYbNW3Wa6BCu3XafyTNuYyKdB20hvoQh9sA4+EK+g/yiFcCmkt9jsCO0slCsgQc3vKlYPzXNn1wuNKlZy2M9SFstOG1o4WGdnVsWPSovhF0kEGvV07EhgAu5MWCGIy7gR1jQz9nhmdu8qtAMErGc3u9LbuiiOTQXVn9hGQWlfPblZBD3Oi0SpKKvhrtE+2DIz2KJVR6qJAzueA8hHKb1MyH3R8odPEUD0SFCsO55js6pSp34QEJSYDv/UnTEbYR9Umy2QBdqAbMRgbtXxBL5Zca8QOdgpOufNmv7InDeJGgXOTG/XsATYmEGvzJLy2hKoDjsubMFCE1oW1pyGNS1FyiSVJIh9s/ZBd54ajfsdhYEBZVXTcNSWkO0MgRK1CHvFkeHJrtM4oUWIZbA5Oat9qIKTdHoEBmfl/jg/LEfGIpt+Iofbjayg61pbJi3w9SWrj/MB9R1hDIO2O3n9bgi4WTKqf7DNtm012O4uz3kgoJ2FBvG248zmxGxAbDOKp+eequX6kRRTGOqAjtxT8oJoAExb68NgqaR6214i3HMdfB9TqSYauuLFbITCpxesLOk12ZJssDuoay0UUALKhVTZEsjOO8UtNqrIU0gWzfuNO0LTdAG1PUauMEv+3EiZZz0wgPOUOXcuOPvMHYzewx13/5CAGfo4s02gsEnZrMMbiDbIoTwjG2VUQASGulZedhjZANIrKRWVbHQObPlbjT7zTMtFN+oum909F1IX2qIH96y3Br12JR7ss0sRKSc16LShAjogiVE9Znv8QP07NWf8jkbL1RFh8JX3U0c3SQ+c1AQTZ9pkVviCDKBUZD7R4jT3cWlnY4voK3tUUtee0LaebZpNLJ1kkmQSknl4BnFjpMqBtIb7qFDhljy+gNDW6OLQJCcQ9bjJe6rWFxBC3FjRg+d64IJABKdX+3+k9EzmYihCMdNdbUg8bdvWrIkfjRTIA/F7ueyrYhVtn1AJJnYEdAJybyUpJoJALBGAhbRhqSXEYhLp6B+xraK2wyr3xecPDJC2kbm1oYV7iYS7u6tMXoKbaSFS6pViQwdgGuGyWK8gOX0iYszGc15hjMBsc6snXFrZ5aBp29lsiJNTa6j+lBfb4+SAvJD5LPgXu58Box0NCBp03HBo2eNrPRAzDdMp4u/NDWOrQqa8c37cQSB0PlgTf1eqxq77T1UdLLvQGlgaiVm3cXncA+0wJ6FN18Y69iRby+Fy29jFitIwM6We/FPth++9nD8PwG8AgX+hP8bWTK+nATbbMdm/noLR4yPvDZbP51y0CaNdF7/3spHvslH4XuZZTHWho5KI3yMC+RQvNyixCh4cwOnZU3A9U9DTocx+YdJjIeC9vQS+4sKPZ27YaUR8/Nxz/bunef7595/HaqFtRBpaxhQIgn6PRyz6PzQ+HnNCPnE9I/IbhjwjdLh6ZFa+Pwmkqp5/eHB/BPt/DRr0TfsbXnz2Rw9hodZWg2WF/WKbpG3+8CtAs48PU9jg8U+v6aexjP/1pVlQL4+NPd/i6AeBbvpT41o5YLGjPZDfNI73XHVh++f2/fCvPzWC8v/JCNQ4uB7E/B3Dz5ZZG07f+Sf9wyPAw711WcNToiehdsf7jw6+jtPryF7X9+vrNZJQE4X27Xaz68qazdzrcl7wtUL6sUT6tWxpd/x0Ok0/Fv4cwUujvmEktyThZ5zYt9vt9Sr8kc7fbsWrjv33RJ/XO/bXhOhfpdzMud2iKAyjKEqwk1FzjTJBhz28XQN3JfHXBPbtdkuvr/Wr4EFZZ/pKUmItSvb4i+P4PV1QcDuqKDz1HzMTlibjL/zHd2GQL2Q/wyAQPvvFJOsWCAgvyEFF+Xq9OaLrxRB/c3r7eSQEwh9er1yX6Wt8kfhJrAdyi69LfqRI37lYbD/qgvia6uKJ7omTjxsTtNjgrrDRTYmE+kHwjaL4YumPAN7Lx6YU6Vsir1dilLyJ/9KDT2o9EF4MpSzqxI7qXNeWdc6Pus7qWiIp6tLkXUDpU/EU1/JHP18UpexIoS0XCAhVSXJMylIUpbBJCfemGzMjCXYqGrAppPelWgkEWZM8LJknutCvloCW2l8qIJJhEuBAiswjHeS4FEdFgE+zIx6BpPcVryy57sJv/gUgj1PNbA8kwPUEEtwisCKwuXStzUryg/ccnN+utrUjGRc+qeU4m3iLxu+ZHb5XDkMBSYIA4MsC9kiNrl91FESaDL/hB/wYgg4swkvxM6/iof2GAxsAUmhLxOzjFgVBSNKSMOLVOHzltPtAs+JbiCPsOeJbjpOcn+8w0Nq6KsC9oSclvJZLwsLIvBbGMrwEN5I6cjDMod85OR+ENlnA5fAOtRAo5Hm8S1yBmfm7JrD5mCiic+7VKuK5ws8cJFH5KkO+g/CaFXPgBJaFUwsvIEH0tXbOWQ1XqKWE/o35vbAkwmVBGdyjZFPX8k6xMJJYvqNId8fhTSDEojeQ90j4PCo3LygTIkkkEcwCEUcXkNhmTTizdKAuwtiASBG1BmyElOe4zXj6JoU3cVK8o8hQGBAAoK8t6eij0JQvMSA4heUSEmx3Yz1eGuFNmwNA/h55HHgejs/AlXikD5PLr1ALas6cCEgtiYQGQjSR/pewvoHAcrj2LREQqE0gA6A0eCpJdGlMiVxALmXkZxkZsa8kI1RZGBh1oyG+XvCNsfHWq1ZBVplEomuwr4j+4nnHFhDDn2KY7qrrFGwDiOitWh930uSS22XsRk5B9aDthKEZQGQ3wFmAyR4zxex1gRQlUWJAInkm2gijsrgijt94d3wzIBKe4SZ7IiMn4ItAcm1J52mizR2LI+IjkEEiAU0ikZwTuxPePCHCiCAivs0OMR9EkFKa4ptsn+SAO6FXrfCyTrkmkhDIeqNb6t2B5zwXMjakJhGAjgxIQQuGTsADpzLIUALFjok295Bw3aByYEhiF0G4mOBVv8wozUYIlP6SKpRQMPiZ2oA1ZB1QuuJSAkMv3gWhzSQyDYwXWmJAAgVTXmI5EoWFyQKCwXOUBTElHgg1HSxWDEhsPqZafLSvfLxypQE8T8tgZAotYGN2pXyAzzdS45QnS+WsWrvmIxpUNm626xc8TfEq7INvJoyJXfoGEgVwtwn9Oh7cSahxUVIWScFIiL8ZdC4swEG8EeGwg8mwikvxzkAltK24GV9vnMyuwYMfuAImCgkppUh4H6fmvXyoQU+GZZk9HMadKXtGjA8I6hE+jocd2lf95TV6qyzAQzoA4jMK6pR3OYleb7P1qQ2JoY4mOkf0jOd2iTKJOlQ+JCS0sYipdpL4dJ389hWPL1OMYF8O1V/jfJ3n62XlHph9+sOPK15+qPLgwKPPdXwB+RjEJCBBEL3TygvZV3oLQUZfo5YeiiF2Dcn3dF+P4nHctZH2Md70eUwmheL9MPM/V26eFwaKj3AzyfxCkUgyRGKQyHvT8AtIbDWGbCEJr4qG0xVp5qn/ory2/4/5OR6P+5tm//j1l6xSq+vir0T/zTgZQfRBiGQtw+NDdqp+PkKyrg0UwcJIGsVsxD4YYDiZdAqH8cV36beR/rcc93R/0PzF2vivdR5xBJ+vIAy/oMgGjYKbnq5jDcmMIEg+VOuylNvlzoACAK4CM/4syS++P8j1Hxj/uN8v0j+VJJYvCH0CZtmlDa/U4aW9wfukz6Bu18tn15GPWYHndZh4NXoLJEqkYMz/El0U4OYPzuei/f43jDe2e65/MFx/ksSzlIppRF7Lwtgut31BS75EcN11jYivKEEQCAArMXhxLFcU/mDsRHNTeZ9ensZT//iLvj/ejM/Edz6bF14WRd3jB6V76cIF5JPZRml4ORCzTSXtX683jLeFEMZXVfnWvDd041z6Rf39R9afxvpL4T9VXXqOiclU7w+0pg4u76fE7gcWiz4seyEDx0NLdD5eHwrovVJoyviOFLRuATFN9DpUlD8z3/PeOxmZqNb3jL7F0Q+DLv0Wmtsgo3ytnQTRX3Tl07snQfDjiR/HW0LhVb/5265f+U/Bj88fffwf3TfzP9Teu5UPZyhO3H6MRJ73OtKqt+DPjSj4MHLAgCfLWUzB0V/c98z3xPwvDJQQWXH9D4U0+3LxYfLOK/8Xxn8AJWrdYmDZcBcAAAAASUVORK5CYII=
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - '*'
          resources:
          - '*'
          verbs:
          - '*'
        - nonResourceURLs:
          - '*'
          verbs:
          - '*'
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: hello-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: hello-operator
          control-plane: controller-manager
        name: hello-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: hello-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: hello-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-require-rbac
                - --metrics-secure
                - --metrics-bind-address=:8443
                - --leader-elect
                - --leader-election-id=hello-operator
                - --health-probe-bind-address=:6789
                env:
                - name: ANSIBLE_GATHERING
                  value: explicit
                image: quay.io/alpaslank/hello-operator:0.0.7
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 6789
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 6789
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 768Mi
                  requests:
                    cpu: 10m
                    memory: 256Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: hello-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: hello-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - hello-operator
  - operator
  - ansible
  links:
  - name: Hello Operator
    url: https://hello-operator.domain
  maintainers:
  - email: alp@perception.com.tr
    name: alp
  maturity: alpha
  provider:
    name: Alpaslan Kaplan
    url: https://perception.com.tr
  replaces: hello-operator.v0.0.5
  version: 0.0.7
