apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-operator
  name: hello-operator-hello-admin-role
rules:
- apiGroups:
  - apigroup.perception.com.tr
  resources:
  - hellos
  verbs:
  - '*'
- apiGroups:
  - apigroup.perception.com.tr
  resources:
  - hellos/status
  verbs:
  - get
